export const FETCH_BITCOIN_LIST_REQUEST = "FETCH_BITCOIN_LIST_REQUEST";
export const FETCH_BITCOIN_LIST_SUCCESS = "FETCH_BITCOIN_LIST_SUCCESS";
export const FETCH_BITCOIN_LIST_FAILURE = "FETCH_BITCOIN_LIST_FAILURE";

export const FETCH_TOP50_BITCOIN_REQUEST = "FETCH_TOP50_BITCOIN_REQUEST";
export const FETCH_TOP50_BITCOIN_SUCCESS = "FETCH_TOP50_BITCOIN_SUCCESS";
export const FETCH_TOP50_BITCOIN_FAILURE = "FETCH_TOP50_BITCOIN_FAILURE";

export const FETCH_MARKET_CHART_REQUEST = "FETCH_MARKET_CHART_REQUEST";
export const FETCH_MARKET_CHART_SUCCESS = "FETCH_MARKET_CHART_SUCCESS";
export const FETCH_MARKET_CHART_FAILURE = "FETCH_MARKET_CHART_FAILURE";

export const FETCH_BITCOIN_BY_ID_REQUEST = "FETCH_BITCOIN_BY_ID_REQUEST";
export const FETCH_BITCOIN_BY_ID_SUCCESS = "FETCH_BITCOIN_BY_ID_SUCCESS";
export const FETCH_BITCOIN_BY_ID_FAILURE = "FETCH_BITCOIN_BY_ID_FAILURE";

export const FETCH_BITCOIN_DETAIL_REQUEST = "FETCH_BITCOIN_DETAIL_REQUEST";
export const FETCH_BITCOIN_DETAIL_SUCCESS = "FETCH_BITCOIN_DETAIL_SUCCESS";
export const FETCH_BITCOIN_DETAIL_FAILURE = "FETCH_BITCOIN_DETAIL_FAILURE";

export const FETCH_SEARCH_COIN_REQUEST = "FETCH_SEARCH_COIN_REQUEST";
export const FETCH_SEARCH_COIN_SUCCESS = "FETCH_SEARCH_COIN_SUCCESS";
export const FETCH_SEARCH_COIN_FAILURE = "FETCH_SEARCH_COIN_FAILURE";
